version: '2'
services:
    primeng-app:
        image: primeng
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://primeng-postgresql:5432/primeng
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://primeng-elasticsearch:9200
        ports:
            - 8080:8080
    primeng-postgresql:
        extends:
            file: postgresql.yml
            service: primeng-postgresql
    primeng-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: primeng-elasticsearch
